[package]
name = "photo_mosaic"
version = "0.1.0"
authors = ["Junsik Hwang <junkwhinger@me.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
